/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    AppFullScreen: typeof import('./src/components/Application/src/AppFullScreen.vue')['default']
    AppGithup: typeof import('./src/components/Application/src/AppGithup.vue')['default']
    AppGitHup: typeof import('./src/components/Application/src/AppGitHup.vue')['default']
    AppLanguage: typeof import('./src/components/Application/src/AppLanguage.vue')['default']
    AppNotification: typeof import('./src/components/Application/src/AppNotification.vue')['default']
    AppProvider: typeof import('./src/components/Application/src/AppProvider.vue')['default']
    AppSearch: typeof import('./src/components/Application/src/search/AppSearch.vue')['default']
    AppSearchFooter: typeof import('./src/components/Application/src/search/AppSearchFooter.vue')['default']
    AppSearchKeyItem: typeof import('./src/components/Application/src/search/AppSearchKeyItem.vue')['default']
    AppSearchModal: typeof import('./src/components/Application/src/search/AppSearchModal.vue')['default']
    AppShrinkIcon: typeof import('./src/components/Application/src/AppShrinkIcon.vue')['default']
    AppThemeMode: typeof import('./src/components/Application/src/AppThemeMode.vue')['default']
    AppUser: typeof import('./src/components/Application/src/AppUser.vue')['default']
    'AppUser.vues': typeof import('./src/components/Application/src/AppUser.vues.vue')['default']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/Icon/src/SvgIcon.vue')['default']
  }
}
